"""initial schema

Revision ID: aacbf65230a8
Revises: 
Create Date: 2026-05-26 22:12:40.608737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacbf65230a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accreditation_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accreditation_reports'))
    )
    op.create_table('badges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badges'))
    )
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('wave', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags'))
    )
    op.create_index(op.f('ix_feature_flags_flag_name'), 'feature_flags', ['flag_name'], unique=True)
    op.create_table('industry_problems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry_problems'))
    )
    op.create_table('jd_pulse_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role_category', sa.String(), nullable=True),
    sa.Column('trending_skills', sa.JSON(), nullable=True),
    sa.Column('analyzed_count', sa.Integer(), nullable=True),
    sa.Column('date_analyzed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jd_pulse_entries'))
    )
    op.create_table('labs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labs'))
    )
    op.create_table('placement_drives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('role_title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_drives'))
    )
    op.create_table('program_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_outcomes'))
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('prompt_template', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions'))
    )
    op.create_index(op.f('ix_prompt_versions_engine_name'), 'prompt_versions', ['engine_name'], unique=False)
    op.create_table('specializations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specializations'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alumni_mentors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('domain_expertise', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alumni_mentors_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alumni_mentors'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_table('course_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_outcomes_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_outcomes'))
    )
    op.create_table('credit_portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('nsqf_level', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_credit_portfolio_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_portfolio'))
    )
    op.create_index(op.f('ix_credit_portfolio_student_id'), 'credit_portfolio', ['student_id'], unique=False)
    op.create_table('draft_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('draft_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('ai_tools_declared', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_draft_submissions_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_submissions'))
    )
    op.create_index(op.f('ix_draft_submissions_assignment_id'), 'draft_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_draft_submissions_student_id'), 'draft_submissions', ['student_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_feedbacks_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_feedbacks_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedbacks'))
    )
    op.create_table('grading_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('professor_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('image_hash', sa.String(), nullable=True),
    sa.Column('rubric_text', sa.String(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('human_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], name=op.f('fk_grading_submissions_professor_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_grading_submissions_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_submissions'))
    )
    op.create_index(op.f('ix_grading_submissions_course_id'), 'grading_submissions', ['course_id'], unique=False)
    op.create_index(op.f('ix_grading_submissions_student_id'), 'grading_submissions', ['student_id'], unique=False)
    op.create_table('hardware_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('equipment_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_hardware_requests_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hardware_requests'))
    )
    op.create_table('learning_roadmaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_learning_roadmaps_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_roadmaps'))
    )
    op.create_table('lectures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_lectures_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lectures'))
    )
    op.create_table('monthly_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('month_year', sa.String(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('concerns', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_monthly_reports_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_reports'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('parent_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_parent_alerts_parent_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_parent_alerts_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_alerts'))
    )
    op.create_table('parent_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_parent_profiles_student_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_parent_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_parent_profiles'))
    )
    op.create_table('performance_trends',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('professor_id', sa.String(), nullable=True),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], name=op.f('fk_performance_trends_professor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_trends'))
    )
    op.create_table('placement_readiness_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_placement_readiness_scores_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_readiness_scores'))
    )
    op.create_table('professor_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_professor_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_professor_profiles'))
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lab_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], name=op.f('fk_projects_lab_id_labs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('review_talking_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('professor_id', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('point', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], name=op.f('fk_review_talking_points_professor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_talking_points'))
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('assessed_by', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('factors_json', sa.JSON(), nullable=True),
    sa.Column('advisory_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_risk_assessments_approved_by_users')),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], name=op.f('fk_risk_assessments_assessed_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_risk_assessments_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    op.create_index(op.f('ix_risk_assessments_student_id'), 'risk_assessments', ['student_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_skill_gaps_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_gaps'))
    )
    op.create_table('student_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('drive_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], name=op.f('fk_student_applications_drive_id_placement_drives')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_student_applications_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_applications'))
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('enrollment_year', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('current_semester', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_student_profiles'))
    )
    op.create_table('syllabus_coverages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('professor_id', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('expected_percentage', sa.Float(), nullable=True),
    sa.Column('actual_percentage', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_syllabus_coverages_course_id_courses')),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], name=op.f('fk_syllabus_coverages_professor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_syllabus_coverages'))
    )
    op.create_table('teaching_intelligence_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('professor_id', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], name=op.f('fk_teaching_intelligence_scores_professor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaching_intelligence_scores'))
    )
    op.create_table('topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_topics_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_table('assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_assessments_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_table('attainment_levels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('co_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], name=op.f('fk_attainment_levels_co_id_course_outcomes')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_attainment_levels_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attainment_levels'))
    )
    op.create_table('co_po_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('co_id', sa.String(), nullable=True),
    sa.Column('po_id', sa.String(), nullable=True),
    sa.Column('correlation_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], name=op.f('fk_co_po_mappings_co_id_course_outcomes')),
    sa.ForeignKeyConstraint(['po_id'], ['program_outcomes.id'], name=op.f('fk_co_po_mappings_po_id_program_outcomes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_co_po_mappings'))
    )
    op.create_table('context_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_context_cards_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context_cards'))
    )
    op.create_table('grading_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('sha256_hash', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['grading_submissions.id'], name=op.f('fk_grading_files_submission_id_grading_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_files'))
    )
    op.create_table('lecture_companions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lecture_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], name=op.f('fk_lecture_companions_lecture_id_lectures')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecture_companions'))
    )
    op.create_table('project_showcases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('is_public', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_showcases_project_id_projects')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_project_showcases_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_showcases'))
    )
    op.create_table('assessment_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_results_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_assessment_results_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_results'))
    )
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_questions_assessment_id_assessments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('assessment_results')
    op.drop_table('project_showcases')
    op.drop_table('lecture_companions')
    op.drop_table('grading_files')
    op.drop_table('context_cards')
    op.drop_table('co_po_mappings')
    op.drop_table('attainment_levels')
    op.drop_table('assessments')
    op.drop_table('topics')
    op.drop_table('teaching_intelligence_scores')
    op.drop_table('syllabus_coverages')
    op.drop_table('student_profiles')
    op.drop_table('student_applications')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_risk_assessments_student_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_table('review_talking_points')
    op.drop_table('projects')
    op.drop_table('professor_profiles')
    op.drop_table('placement_readiness_scores')
    op.drop_table('performance_trends')
    op.drop_table('parent_profiles')
    op.drop_table('parent_alerts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('monthly_reports')
    op.drop_table('lectures')
    op.drop_table('learning_roadmaps')
    op.drop_table('hardware_requests')
    op.drop_index(op.f('ix_grading_submissions_student_id'), table_name='grading_submissions')
    op.drop_index(op.f('ix_grading_submissions_course_id'), table_name='grading_submissions')
    op.drop_table('grading_submissions')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_draft_submissions_student_id'), table_name='draft_submissions')
    op.drop_index(op.f('ix_draft_submissions_assignment_id'), table_name='draft_submissions')
    op.drop_table('draft_submissions')
    op.drop_index(op.f('ix_credit_portfolio_student_id'), table_name='credit_portfolio')
    op.drop_table('credit_portfolio')
    op.drop_table('course_outcomes')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('alumni_mentors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_prompt_versions_engine_name'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_table('program_outcomes')
    op.drop_table('placement_drives')
    op.drop_table('labs')
    op.drop_table('jd_pulse_entries')
    op.drop_table('industry_problems')
    op.drop_index(op.f('ix_feature_flags_flag_name'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_table('courses')
    op.drop_table('badges')
    op.drop_table('accreditation_reports')
    # ### end Alembic commands ###
